name: Docker Image CI

on:
  push:
    tags:
      # Build only tagged releases
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: starcraft66
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: ./build_all_images.sh
