name: Master Branch Image

on:
  push:
    branches:
      # Build only the master branch
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build_master_image.sh
      env:
        DOCKER_HUB_USERNAME: starcraft66
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        GITHUB_PKG_USERNAME: starcraft66
        GITHUB_PKG_PASSWORD: ${{ secrets.GITHUB_TOKEN_OWNED }}