name: Tagged Images

on:
  push:
    tags:
      # Build only tagged releases
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build_tagged_images.sh
      env:
        DOCKER_HUB_USERNAME: starcraft66
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        GITHUB_PKG_USERNAME: starcraft66
        GITHUB_PKG_PASSWORD: ${{ secrets.GITHUB_TOKEN_OWNED }}
